### ISSUE TITLE
Update Makefiles 

### ISSUE THREAD

**Issue by gedw99** [lerenn/asyncapi-codegen#106]
what the Readme says and what the makefiles do is a bit confusing.

Hello world generates 2 apps.

But the root README.md only shows generating one.

Perhaps just alter the hello world Makefile to also do the code gen. The sub Makefile does the docker compose running as it does now.

**Comment by lerenn** [comment]
Hello World generates 2 apps, one for Kafka and one for NATS.

I won't alter the Makefile to do the code generation as this is done by `go generate`.

However, I do understand the confusion, so I'll make it clearer in the README, and perhaps mutualize the code generation of both app.

**Comment by lerenn** [comment]
Feel free to reopen if needed !

**Comment by gedw99** [comment]
Thanks 🙏
