### ISSUE TITLE
Override snake case for JSON struct tags

### ISSUE THREAD

**Issue by will-rowe** [lerenn/asyncapi-codegen#129]
Hi.

Thanks for a great package! I was wondering if it is possible to specify a different case for the json struct tags in the generated models? I.e. have camelCase instead?

**Comment by will-rowe** [comment]
Hi - I ended up forking and adding a helper to change from the default snake case, eg:

```
func ConvertCase(sentence, caseFormat string) string {
	str := stringy.New(sentence)
	switch caseFormat {
	case "camel":
		camel := str.CamelCase()
		return stringy.New(camel).LcFirst()
	case "kebab":
		val := str.KebabCase()
		return val.ToLower()
	default:
		val := str.SnakeCase()
		return val.ToLower()
	}
}
```

I updated the schema template and added an extension so you can override the default:

```
ExtJSONTagCase string `json:"x-json-tag-case"`
```

Let me know if this is something you want upstream and I can make an MR.

**Comment by lerenn** [comment]
Hello @will-rowe ! Thanks for the kind words ☺️

Regarding your proposal, it's a great idea !! If you're okay to do a MR to merge your work, I would be really happy to integrate it.

**Comment by lerenn** [comment]
If you're still good with the MR and if you have time to do so, I would be nice to have your helper ! :)

**Comment by hound672** [comment]
I wonder why should use extra tag for it?
We can use tag from specification as default and if you need to convert then specify with tag?

**Comment by lo00l** [comment]
Agree with @hound672. To be honest, I don't understand why it's even necessary to convert property key names to snake_case (or to something else).

Now I have specification with the following schema:
```yaml
IndividualExposureLimitsSet:
  type: object
  additionalProperties: false
  properties:
    Separate Uuid Thresholds:
      $ref: '#/components/schemas/SeparateUUIDExposureLimitValues'
```

This specification is provided by other team so I cannot modify it.

When I generate types, I get
```go
type IndividualExposureLimitsSetSchema struct {
	SeparateUuidThresholds *SeparateUUIDExposureLimitValuesSchema `json:"separate _uuid _thresholds"`
}
```

Well, seems it will not work at all for me :) 

What's about adding new generation option `convert-keys` with possible values, for example, `snake`, `camel`, `kebab`, `none` (default is `snake` to make it backward compatible)?

So we could run generation like this: `asyncapi-codegen -g types -i asyncapi.yaml -o ./models.gen.go -p test --convert-keys none`.

If you think it's ok then I could implement it.

P.S.: I would be happy if we could just remove `snakeCase` call from [schema_definition.tmpl](https://github.com/lerenn/asyncapi-codegen/blob/main/pkg/codegen/generators/v2/templates/schema_definition.tmpl#L18) but it would break backward compatibility.

**Comment by lerenn** [comment]
I really like the generation option ! To be honest, I don't remember why I choose `snake case`. Maybe because that why I (wrongly) assume JSON was using.

So I'm all for doing the `--convert-keys` to avoid breaking existing configuration, but I would be for the `none` option as default.

It would break some configuration without changing the command line, but:
 - there is not a lot of users now
 - this is not a v1 yet
 - it's based on the false belief that payloads needed to be snake case in JSON (like some Open API tools)
 - it would be easy to correct by adding the command line option

Thanks for pointing that out !

**Comment by lerenn** [comment]
Fixed by https://github.com/lerenn/asyncapi-codegen/pull/199
