### ISSUE TITLE
Support AsyncAPI v3

### ISSUE THREAD

**Issue by gnuletik** [lerenn/asyncapi-codegen#130]
Hi,

Thanks for this project!

I wanted to give it a try but it doesn't seem to support AsyncAPI v3.

```
$ asyncapi-codegen -i ./asyncapi-v3.yaml -p asyncapi -o ./asyncapi.gen.go
 --- Anomalies detected in specification ---
version "3.0.0" is not supported
```

Any plan to support it?

Thanks!

**Comment by lerenn** [comment]
Hi @gnuletik, thanks for reaching out !

Yes, I'll write the feature to support version 3, it should be available in the next weeks. 

I'll let you know when it will be ready :smiley:

**Comment by lerenn** [comment]
Sorry, I didn't have the time to work on it the past 2 weeks, but I'll work on it next week :)

**Comment by lerenn** [comment]
@gnuletik, please let me know if there more to implement or some bugs :)

**Comment by gnuletik** [comment]
Thanks, it works like a charm!

**Comment by lerenn** [comment]
Thanks for the king words !
It took a bit of code to implement it, so there is still some bugs, but it's on the right path 😄
