### ISSUE TITLE
Ref to schema in other file?

### ISSUE THREAD

**Issue by lo00l** [lerenn/asyncapi-codegen#193]
First of all, thank you for your package! This is exactly what I was looking for.

Suppose I have 2 yaml files:
`asyncapi.yaml`:
```yaml
asyncapi: 2.6.0
info:
  title: Test
  version: 1.0.0

defaultContentType: application/json

channels:
  test:
    description: Test
    subscribe:
      operationId: Test
      message:
        $ref: "#/components/messages/TestMessage"
    bindings:
      kafka:
        is: topic

components:
  messages:
    TestMessage:
      messageId: TestMessage
      name: TestMessage
      payload:
        $ref: "common.yaml#/components/schemas/Foo"
```

`common.yaml`:
```yaml
components:
  schemas:
    Foo:
      type: object
      properties:
        bar:
          type: string
```

When I run `asyncapi-codegen -g types -i asyncapi.yaml -o ./models.gen.go -p test` I get error `error when using AsyncAPI: invalid reference: empty target for schema reference "common.yaml#/components/schemas/Foo"`.

Is it even possible to define my schemas in separate file to make it reusable?

**Comment by lerenn** [comment]
Hello @lo00l ! Thanks for your interest in this project ☺️ 

Well, this is a really interesting feature which is not yet developed. There is [another issue](https://github.com/lerenn/asyncapi-codegen/issues/192) with kinda the same request, so I'll do a PR to have this ASAP as it should not be difficult (I aim for the end of the week, but no guarantee).
