### ISSUE TITLE
Nats Jetstream: consuming a message without subscription causes deadlock in the consumer

### ISSUE THREAD

**Issue by mymdz** [lerenn/asyncapi-codegen#206]
Steps to reproduce:

1. Generate multiple operations: `A` and `B`
2. Subscribe to a specific subject (`A`) using UserController, without UserSubscriber implementation
3. Send a message to `B`. A warning will be printed: `Received message for not subscribed channel 'B'. Message will be ack'd.`
4. Send a message to A - nothing happens

There is a deadlock because of writing to nil channel

**Comment by mymdz** [comment]
Fixed with https://github.com/lerenn/asyncapi-codegen/pull/207

**Comment by lerenn** [comment]
Hello @mymdz ! Good jobs ! Thanks for taking the time to report the bug AND to bring a fix ! ☺️ 
I'll review it ASAP and I'll merge it (maybe not today, but tomorrow).
