### ISSUE TITLE
AsyncAPI v3: support proper Message references from the Operation

### ISSUE THREAD

**Issue by wizzardich** [lerenn/asyncapi-codegen#211]
## Current Behaviour

Given the following configuration of the `operation`, `channel` and `message` objects:

```yaml
asyncapi: 3.0.0
info:
  title: event
  version: 0.1.0
channels:
  eventSuccess:
    address: some.random.topic
    messages:
      eventSuccessMessage:
        $ref: '#/components/messages/EventSuccess'
operations:
  handleEventSuccess:
    action: 'receive'
    channel:
      $ref: '#/channels/eventSuccess'
    messages:
      - $ref: '#/channels/eventSuccess/messages/eventSuccessMessage'
components:
  messages:
    EventSuccess:
      payload:
        type: object
        properties:
          timestamp:
            type: integer
            description: The timestamp of the event
```

The execution of `asyncapi-codegen` fails while parsing the spec:

```sh
✘ asyncapi-codegen -i api/asyncapi/client/events.yml -o asyncapi.gen.go -g types
Error: error when using AsyncAPI: invalid reference: cannot cast "#/channels/eventSuccess/messages/eventSuccessMessage" into 'Message' (type is "*asyncapiv3.Channel")
```

According to the [AsyncAPI v3 specification](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationObject), the `Operation` object's `messages` field is supposed to reference a subset of channel's messages.

Currently the following would work with `asyncapi-codegen`:

```yaml
asyncapi: 3.0.0
info:
  title: event
  version: 0.1.0
channels:
  eventSuccess:
    address: some.random.topic
    messages:
      eventSuccessMessage:
        $ref: '#/components/messages/EventSuccess'
operations:
  handleEventSuccess:
    action: 'receive'
    channel:
      $ref: '#/channels/eventSuccess'
    messages:
      - $ref: '#/components/messages/EventSuccess'
components:
  messages:
    EventSuccess:
      payload:
        type: object
        properties:
          timestamp:
            type: integer
            description: The timestamp of the event
```

But AsyncAPI parser that [AsyncAPI Studio](https://studio.asyncapi.com/) utilizes breaks on this with `Operation message does not belong to the specified channel.`. If I understand correctly, this is the spec's intention.

## Expected Behaviour

The messags refs are resolved correctly according to the spec.

## Notes

- It seems like the crux of the problem is [here](https://github.com/lerenn/asyncapi-codegen/blob/main/pkg/asyncapi/v3/specification.go#L270).
- It honestly took me a while to wrap my head around this, but the spec says:
    > A list of $ref pointers pointing to the supported [Message Objects](https://www.:.com/docs/reference/specification/v3.0.0#messageObject) that can be processed by this operation. It MUST contain a subset of the messages defined in the [channel referenced in this operation](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationObjectChannel), and MUST NOT point to a subset of message definitions located in the [Messages Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#componentsMessages) in the [Components Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#componentsObject) or anywhere else.

  Seemingly that means that actual references to `#/components/messages/...` are incorrect in the operation, which really does give me a headache. This seems to be the intention though, to guarantee that only messages defined in the channel are used in the operation.

PS. Thanks again :)

**Comment by lerenn** [comment]
I see ! Well, I probably won't have time to tackle this today, but I'll do it in the next days.

Thanks again for reporting this ! :)

**Comment by lerenn** [comment]
Also thanks for providing examples, it really helps me to reproduce and write non-regression tests to avoid any return of this bug !

**Comment by wizzardich** [comment]
I know the pain of trying to figure out the repro, no worries! Glad to hear that helps :)
