### ISSUE TITLE
Converting a date format "YYYY-MM-DD" to a time.time gives an error

### ISSUE THREAD

**Issue by jturc** [lerenn/asyncapi-codegen#222]
I have an asyncapi contract with a property :
`
bladate:
	description: Date with format "YYYY-MM-DD"
	type: string
	format: date
	example: '2024-09-15'
`
It currently generates me a time.time but when it tries to unmarshall it, it can't parse it to the time.time type because of the format.
I'm using asyncapi v2.6.0

**Comment by jturc** [comment]
As you can see here : https://v2.asyncapi.com/docs/reference/specification/v2.6.0#dataTypeFormat.  A format date should respect As defined by full-date - [RFC3339](https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6) vs datetime should respect As defined by date-time - [RFC3339](https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6).  Right now we are converting date to time.time but the parse method of time.time returns and error with the full date format of RFC3339.  Date and datetime formats should not be treated the same way in the code.  A quick solution here would be to let a format date in a string instead of a time.time.

**Comment by lerenn** [comment]
Arf, sorry about that. I'll tackle this in the next day.

Thanks for pointing it out !
