### ISSUE TITLE
field validation - bug when handling nil/empty values.

### ISSUE THREAD

**Issue by TheSadlig** [lerenn/asyncapi-codegen#228]
Hello,

I introduced a bug in this PR: https://github.com/lerenn/asyncapi-codegen/pull/218

The validation on non-required fields should not fail if the field is absent/empty.

For Example:
```
EnumProp:
  type: string
  enum:
    - "red"
    - "amber"
    - "green"
``` 

Generates:
```
   EnumProp             *string  `json:"EnumProp" validate:"oneof=red amber green"`
```

When validating an empty struct, I would expect no error, since the field is not required, and the error should only happen if the field is defined but wrong.

The fix is actually quite simple, and we should generate the field with "omitempty" (see https://stackoverflow.com/a/72916039):

```
   EnumProp             *string  `json:"EnumProp" validate:"omitempty,oneof=red amber green"`
```

A PR is on its way to fix this :)

**Comment by lerenn** [comment]
Fixed in PR https://github.com/lerenn/asyncapi-codegen/pull/229
