### ISSUE TITLE
Memory leak in SubscribeTo

### ISSUE THREAD

**Issue by nuttert** [lerenn/asyncapi-codegen#240]
Hey!
I noticed that my server memory grows linearly:
<img width="851" alt="image" src="https://github.com/lerenn/asyncapi-codegen/assets/35408275/46d8cfd0-0060-4994-9e76-2cc72e3ee68a">
then created two snapshots of the heap and visualized their difference:
<img width="996" alt="image" src="https://github.com/lerenn/asyncapi-codegen/assets/35408275/b3080b72-408e-4196-9663-4a372f252c7f">

And think that the problem in the code(in the SubscribeTo method):
```go
 ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, acknowledgeableBrokerMessage.String())
 ```
 First of all, why do you serialize full message? The message could be 8 mb and it seems that if we do not a debug, we don't need it.
And second point, that I don't understand why the sub context has not finished, also there are no deadlines for it. I thought may be problem in my code that it holds the context, but as you can see the problem also in a ping handler(the server gets about 3000 ping every minute), it almost empty without logic

**Comment by lerenn** [comment]
Hello @nuttert ! Thanks for taking time to fill in an issue :)

Arf, the serialization was intended for debug purposes if someone wanted to log the message content.

I was expecting the context to just be garbage collected after the call.
I'll add a deadline to it. Thanks for pointing this !

Feel free to give more info if you stumble on anything else !
