### ISSUE TITLE
Wrong usage for validator's `required` directive

### ISSUE THREAD

**Issue by TheSadlig** [lerenn/asyncapi-codegen#259]
Hello,

The definition for `required` in the asyncapi specification, and the validator's `required` are different:
- For asyncapi, the field needs to be present BUT can be empty
- For validator, the fields needs to be present  AND cannot be empty - https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Required

Because of this behaviour, the validator cannot be used to validate most structs.

What I would recommend:

1. Remove `required` for non-pointer fields
2. Add a flag to force all fields to be generated as pointer.

Without the point 2., we have no way of knowing whether the incoming message was absent or not, since non-pointer struct will be initialized with empty/zero-value.
This could be the default behaviour (in a future version ?), but since this would have large impacts on users, I figured having it opt-in was best for now

Thanks

**Comment by lerenn** [comment]
Hi @TheSadlig, thanks for the issue :)

For this version, a flag is indeed better and in a future version it could be a default behavior.

Feel free to propose a PR if you need this, as I don't have a lot of time in my hands actually.
