### ISSUE TITLE
Feature request: support custom Go type names

### ISSUE THREAD

**Issue by leejuyuu** [lerenn/asyncapi-codegen#48]
Hello, thanks for making this useful tool!

I would like to suggest adding support for an extension to allow specifying Go types, like `x-go-type`  from oapi-codegen.
Ref https://github.com/deepmap/oapi-codegen/pull/212.

If you think this is feasible, I can try drafting up a PR later.

**Comment by lerenn** [comment]
Hello @leejuyuu !

Thanks for your interest in this repo ! It's still a side project that I maintain for my own projects but I'd like very much to make it useful for everyone one (like deepmap/oapi-codegen). 

There is still plenty to do, so I'm really interested on working on troubles and features to improve it for everyone!

Concerning `x-go-types`, I think it would demand a bit of work but it would be definitely possible and something really interesting!

I'll take care of your other issues before this one but tell me if you prefer to tackle it on your side or if you prefer to let me do it (to avoid double work).

**Comment by leejuyuu** [comment]
Hello @lerenn, thanks for the reply!

I would like to give this a try! Sounds like it is going to take some time. I will reply here if I get stuck or have any further questions.

**Comment by lerenn** [comment]
Perfect, just tell me if there anything I can do or help to.
